"""add agent clarification and files

Revision ID: 470555d27864
Revises: f9b54e9de6fd
Create Date: 2026-05-12 10:58:19.029713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '470555d27864'
down_revision: Union[str, None] = 'f9b54e9de6fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
