"""add agent generation tables

Revision ID: 4ddabf7df710
Revises: 9cc704510f7e
Create Date: 2026-05-12 11:29:11.710680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4ddabf7df710'
down_revision: Union[str, None] = '9cc704510f7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
