"""add agent generation tables

Revision ID: 82ea603f00d7
Revises: 4ddabf7df710
Create Date: 2026-05-12 12:19:07.733391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '82ea603f00d7'
down_revision: Union[str, None] = '4ddabf7df710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_clarifications',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_clarifications_agent_id'), 'agent_clarifications', ['agent_id'], unique=False)
    op.create_table('agent_files',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'path', name='uq_agent_file_path')
    )
    op.create_index(op.f('ix_agent_files_agent_id'), 'agent_files', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_files_agent_id'), table_name='agent_files')
    op.drop_table('agent_files')
    op.drop_index(op.f('ix_agent_clarifications_agent_id'), table_name='agent_clarifications')
    op.drop_table('agent_clarifications')
    # ### end Alembic commands ###
