"""add agent generation tables

Revision ID: 9cc704510f7e
Revises: 470555d27864
Create Date: 2026-05-12 11:26:23.160236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9cc704510f7e'
down_revision: Union[str, None] = '470555d27864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
