"""add agent clarification and files

Revision ID: f9b54e9de6fd
Revises: c7f1a9d2e4b6
Create Date: 2026-05-12 10:57:38.466679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f9b54e9de6fd'
down_revision: Union[str, None] = 'c7f1a9d2e4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
